import { StyleSheet } from 'react-native';
import { theme } from '../theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: theme.colors.white,
  },
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: theme.spacing.md,
    backgroundColor: theme.colors.white,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.colors.background,
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    fontSize: 17,
    fontWeight: '700',
    color: theme.colors.textPrimary,
    letterSpacing: -0.3,
  },
  scrollContent: {
    paddingBottom: 36,
  },
  statusSection: {
    backgroundColor: theme.colors.white,
    padding: 20,
    marginBottom: 12,
  },
  statusHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: theme.radius.pill,
  },
  statusBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  orderIdText: {
    fontSize: 15,
    fontWeight: '700',
    color: theme.colors.textPrimary,
    marginBottom: 4,
    letterSpacing: 0.5,
  },
  dateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  dateText: {
    fontSize: 13,
    color: theme.colors.textMuted,
    fontWeight: '500',
  },
  stepperWrapper: {
    paddingHorizontal: 10,
  },
  section: {
    marginTop: 12,
    paddingHorizontal: 16,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    gap: 8,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: theme.colors.textPrimary,
    flex: 1,
    letterSpacing: -0.2,
  },
  vendorStatusBadge: {
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: theme.radius.pill,
  },
  vendorStatusText: {
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  card: {
    backgroundColor: theme.colors.white,
    borderRadius: theme.radius.lg,
    padding: theme.spacing.md,
    ...theme.shadows.soft,
  },
  itemsCard: {
    backgroundColor: theme.colors.white,
    borderRadius: theme.radius.lg,
    paddingHorizontal: theme.spacing.md,
    ...theme.shadows.soft,
  },
  itemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.borderLight,
  },
  itemInfo: {
    flex: 1,
    marginRight: 12,
  },
  itemName: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.textPrimary,
    marginBottom: 3,
    letterSpacing: -0.1,
  },
  itemQty: {
    fontSize: 12,
    color: theme.colors.textMuted,
    fontWeight: '500',
    lineHeight: 18,
  },
  itemPrice: {
    fontSize: 15,
    fontWeight: '800',
    color: theme.colors.primary,
    letterSpacing: -0.2,
  },
  priceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  priceLabel: {
    fontSize: 14,
    color: theme.colors.textMuted,
    fontWeight: '500',
  },
  priceValue: {
    fontSize: 14,
    color: theme.colors.textPrimary,
    fontWeight: '600',
  },
  totalRow: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: theme.colors.border,
  },
  totalLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: theme.colors.textPrimary,
  },
  totalValue: {
    fontSize: 20,
    fontWeight: '800',
    color: theme.colors.primary,
    letterSpacing: -0.3,
  },
  addressText: {
    fontSize: 14,
    color: theme.colors.textPrimary,
    lineHeight: 21,
    fontWeight: '500',
  },
  reviewProposalsButton: {
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.accent,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: theme.radius.lg,
    marginTop: 16,
    gap: 8,
    ...theme.shadows.soft,
  },
  reviewProposalsText: {
    color: theme.colors.white,
    fontWeight: '700',
    fontSize: 14,
  },
  rateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.primary,
    paddingVertical: 11,
    borderRadius: theme.radius.lg,
    marginTop: 10,
    gap: 6,
  },
  rateButtonText: {
    color: theme.colors.white,
    fontWeight: '700',
    fontSize: 14,
  },
  weightContainer: {
    marginTop: 2,
  },
  proposedWeightText: {
    color: theme.colors.primary,
    fontWeight: '600',
    marginTop: 2,
  },
  confirmationCard: {
    marginTop: 10,
    backgroundColor: theme.colors.primaryXLight,
    borderRadius: theme.radius.lg,
    padding: 20,
    borderWidth: 1,
    borderColor: theme.colors.primaryLight,
    alignItems: 'center',
  },
  confirmationTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: theme.colors.textPrimary,
    marginBottom: 8,
    textAlign: 'center',
  },
  confirmationBody: {
    fontSize: 13,
    color: theme.colors.textMuted,
    textAlign: 'center',
    marginBottom: 12,
    lineHeight: 20,
  },
  countdownText: {
    fontSize: 24,
    fontWeight: '800',
    color: theme.colors.accent,
    marginBottom: 20,
    letterSpacing: -0.5,
  },
  confirmButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.primary,
    paddingVertical: 13,
    paddingHorizontal: 30,
    borderRadius: theme.radius.lg,
    width: '100%',
    marginBottom: 10,
    gap: 8,
  },
  confirmButtonText: {
    color: theme.colors.white,
    fontWeight: '700',
    fontSize: 15,
  },
  cancelConfirmButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.errorLight,
    paddingVertical: 13,
    paddingHorizontal: 30,
    borderRadius: theme.radius.lg,
    width: '100%',
    borderWidth: 1,
    borderColor: '#FECACA',
    gap: 8,
  },
  cancelConfirmButtonText: {
    color: theme.colors.error,
    fontWeight: '700',
    fontSize: 15,
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  cancellationBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: theme.colors.errorLight,
    borderRadius: theme.radius.lg,
    padding: 14,
    marginTop: 12,
    gap: 10,
    borderWidth: 1,
    borderColor: '#FECACA',
  },
  cancellationLabel: {
    fontSize: 12,
    color: '#991B1B',
    fontWeight: '700',
    marginBottom: 2,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  cancellationText: {
    fontSize: 13,
    color: '#DC2626',
    lineHeight: 18,
  },
  vendorCancellationBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: theme.colors.errorLight,
    borderRadius: theme.radius.md,
    padding: 10,
    marginTop: 8,
    gap: 8,
    borderWidth: 1,
    borderColor: '#FECACA',
  },
  vendorCancellationText: {
    fontSize: 13,
    color: '#DC2626',
    flex: 1,
    lineHeight: 18,
  },
  countdownBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fef3c7',
    borderRadius: theme.radius.lg,
    padding: 14,
    marginBottom: 12,
    gap: 12,
    borderWidth: 1,
    borderColor: '#fcd34d',
  },
  countdownBannerUrgent: {
    backgroundColor: '#fee2e2',
    borderColor: '#fca5a5',
  },
  countdownBannerTitle: {
    fontSize: 12,
    color: '#92400e',
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  countdownBannerTitleUrgent: {
    color: '#991b1b',
  },
  countdownBannerTimer: {
    fontSize: 22,
    fontWeight: '800',
    color: '#b45309',
    fontVariant: ['tabular-nums'],
  },
  countdownBannerTimerUrgent: {
    color: '#dc2626',
  },
});
